"""empty message

Revision ID: 2ab52f1b34ec
Revises: 6d612d00c983
Create Date: 2023-02-18 14:16:13.102207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ab52f1b34ec'
down_revision = '6d612d00c983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
