"""empty message

Revision ID: 6d612d00c983
Revises: cf66e8685be7
Create Date: 2023-02-08 22:54:36.242478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d612d00c983'
down_revision = 'cf66e8685be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('art-users')
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'artusers', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('art-users',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"art-users_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='art-users_pkey'),
    sa.UniqueConstraint('username', name='art-users_username_key')
    )
    # ### end Alembic commands ###
