"""empty message

Revision ID: cf66e8685be7
Revises: 5418102b62ab
Create Date: 2023-02-08 20:58:52.725503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cf66e8685be7'
down_revision = '5418102b62ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artusers')
    op.drop_table('file-content')
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('filecontent', schema=None) as batch_op:
        batch_op.drop_column('url')

    op.create_table('file-content',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"file-content_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('filename', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data', postgresql.BYTEA(), autoincrement=False, nullable=False),
    sa.Column('rendered_data', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('pic_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='file-content_pkey')
    )
    op.create_table('artusers',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='artusers_pkey'),
    sa.UniqueConstraint('username', name='artusers_username_key')
    )
    # ### end Alembic commands ###
